// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechVerseX.TechnologyService.Infrastructure.Persistence;

#nullable disable

namespace TechVerseX.TechnologyService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TechnologyDbContext))]
    [Migration("20260904091808_BidangDanKematanganKonten")]
    partial class BidangDanKematanganKonten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("technology")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.Field", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_fields_display_order");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_fields_name");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_fields_slug");

                    b.ToTable("fields", "technology");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000001"),
                            DisplayOrder = 1,
                            Name = "AI & Machine Learning",
                            Priority = "Core",
                            Slug = "ai-machine-learning",
                            Summary = "Fondasi: ML klasik, deep learning, LLM, computer vision, NLP, reinforcement learning, multimodal."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000002"),
                            DisplayOrder = 2,
                            Name = "AI Agents",
                            Priority = "Core",
                            Slug = "ai-agents",
                            Summary = "Lapisan orkestrasi: tool use, MCP, A2A, memori agen, evals, keamanan agen, human-in-the-loop."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000003"),
                            DisplayOrder = 3,
                            Name = "Cybersecurity",
                            Priority = "Core",
                            Slug = "cybersecurity",
                            Summary = "Ethical hacking, SOC, malware, reverse engineering, keamanan awan, dan keamanan AI."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000004"),
                            DisplayOrder = 4,
                            Name = "Cloud & Infrastructure",
                            Priority = "Core",
                            Slug = "cloud-infrastructure",
                            Summary = "Docker, Kubernetes, tiga hyperscaler, DevOps, dan platform engineering. Nama lebar dipertahankan dengan sengaja - lihat ADR-010."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000005"),
                            DisplayOrder = 5,
                            Name = "Data Engineering",
                            Priority = "Core",
                            Slug = "data-engineering",
                            Summary = "Lapisan yang menentukan proyek AI hidup atau mati: ingestion, orkestrasi, lakehouse, format tabel terbuka, streaming, kontrak data, pemodelan."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000006"),
                            DisplayOrder = 6,
                            Name = "IoT",
                            Priority = "Core",
                            Slug = "iot",
                            Summary = "Konektivitas, firmware & RTOS, Matter/Thread, gateway tepi, keamanan perangkat, IIoT, telemetri deret waktu, dan satu halaman jembatan TinyML."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000007"),
                            DisplayOrder = 7,
                            Name = "Edge AI",
                            Priority = "Supporting",
                            Slug = "edge-ai",
                            Summary = "AI yang berjalan di perangkat: kuantisasi, distilasi, NPU, runtime on-device. Bidang sendiri, BUKAN anak IoT - tinyML Foundation sendiri sudah berganti nama jadi Edge AI Foundation."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000008"),
                            DisplayOrder = 8,
                            Name = "Robotics",
                            Priority = "Supporting",
                            Slug = "robotics",
                            Summary = "ROS2, humanoid, drone, kendaraan otonom, dan Robotics AI yang pindah ke sini dari AI & ML."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-000000000009"),
                            DisplayOrder = 9,
                            Name = "Quantum Computing",
                            Priority = "Supporting",
                            Slug = "quantum-computing",
                            Summary = "Qubit, Qiskit, algoritma kuantum, kriptografi kuantum. Era qubit logis; keunggulan komersial belum ada."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-00000000000a"),
                            DisplayOrder = 10,
                            Name = "Biotechnology",
                            Priority = "Supporting",
                            Slug = "biotechnology",
                            Summary = "CRISPR, AlphaFold, biologi sintetis, kesehatan digital."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-00000000000b"),
                            DisplayOrder = 11,
                            Name = "Blockchain",
                            Priority = "Supporting",
                            Slug = "blockchain",
                            Summary = "Smart contract, Ethereum, Solana, Layer 2, DeFi."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-00000000000c"),
                            DisplayOrder = 12,
                            Name = "Renewable Energy",
                            Priority = "Supporting",
                            Slug = "renewable-energy",
                            Summary = "Solar PV, angin, panas bumi, hidro, bioenergi & SAF, hidrogen hijau, integrasi jaringan & penyimpanan, ekonomi & kebijakan. Fusi TIDAK di sini - lihat ADR-010."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-00000000000d"),
                            DisplayOrder = 13,
                            Name = "Space Technology",
                            Priority = "Peripheral",
                            Slug = "space-technology",
                            Summary = "Konektivitas LEO, akses ke orbit, smallsat, segmen darat, observasi Bumi, GNSS/PNT, keselamatan orbit. Irisan terkuatnya: 3GPP NTN."
                        },
                        new
                        {
                            Id = new Guid("f1e10000-0000-7000-8000-00000000000e"),
                            DisplayOrder = 14,
                            Name = "XR (AR/VR/MR)",
                            Priority = "Peripheral",
                            Slug = "xr",
                            Summary = "Realitas diperluas. Dipertahankan sebagai pintu pencarian, tapi sengaja tidak diinvestasikan - lihat ADR-010."
                        });
                });

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Maturity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_technologies_field_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_technologies_slug");

                    b.HasIndex("FieldId", "Maturity")
                        .HasDatabaseName("ix_technologies_field_maturity");

                    b.ToTable("technologies", "technology");
                });

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.TechnologyRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromTechnologyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ToTechnologyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromTechnologyId", "ToTechnologyId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_technology_relationships_edge");

                    b.ToTable("technology_relationships", "technology");
                });

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.Technology", b =>
                {
                    b.HasOne("TechVerseX.TechnologyService.Domain.Field", null)
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.TechnologyRelationship", b =>
                {
                    b.HasOne("TechVerseX.TechnologyService.Domain.Technology", null)
                        .WithMany("Relationships")
                        .HasForeignKey("FromTechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechVerseX.TechnologyService.Domain.Technology", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
